### ISSUE TITLE
react native 可以用吗

### ISSUE THREAD

**Issue by Jayxiang** [imwangji/pinyinOrder#1]

**Comment by imwangji** [comment]
这是一个标准的JS文件，我没有在react native里面尝试过，如果你尝试了的话，可以告诉我你的进展吗？

**Comment by b9AobJ** [comment]
貌似不可以引入使用，是否可以查看下怎么去支持他？

**Comment by Jayxiang** [comment]
我换了另一个使用的

**Comment by imwangji** [comment]
> 貌似不可以引入使用，是否可以查看下怎么去支持他？

因为我没用过RN，所以我不知道该如何搞。但是我觉得相当有必要。

**Comment by imwangji** [comment]
> 我换了另一个使用的

可以告诉我是你改用了哪个库吗？我想去学学源码：）

**Comment by Jayxiang** [comment]
https://github.com/waterchestnut/pinyin        他的好像也是一个js库

**Comment by Kerita** [comment]
感谢 @imwangji 开源这个库。

我在RN试了可以用，但是 package.json 里面 main 字段路径写错了，需要修改一下。

其次是 dic.js 里面没有“喆”字，导致在调这个方法的时候出错了 getCharactorFirstPinYinWord。

有空我来提个 PR。

**Comment by imwangji** [comment]
> https://github.com/waterchestnut/pinyin 他的好像也是一个js库

他好像没有排序功能。？

**Comment by imwangji** [comment]
> 感谢 @imwangji 开源这个库。
> 
> 我在RN试了可以用，但是 package.json 里面 main 字段路径写错了，需要修改一下。
> 
> 其次是 dic.js 里面没有“喆”字，导致在调这个方法的时候出错了 getCharactorFirstPinYinWord。
> 
> 有空我来提个 PR。

老哥快来提PR吧。我们一起完善这个代码。我个人能力实在有限。我不是一个好coder  😓
